ALTER DATABASE SQL2012SBS
    ADD FILEGROUP FullTextCatalog
GO
ALTER DATABASE SQL2012SBSFS
    ADD FILEGROUP FullTextCatalog
GO
ALTER DATABASE SQL2012SBS
    ADD FILE (NAME = N'SQL2008SBSFT', FILENAME = N'D:\SQL2012SBSFT.ndf')
    TO FILEGROUP FullTextCatalog
GO
ALTER DATABASE SQL2012SBSFS
    ADD FILE (NAME = N'SQL2008SBSFSFT', FILENAME = N'D:\SQL2012SBSFSFT.ndf')
    TO FILEGROUP FullTextCatalog
GO