CREATE DATABASE SQL2012SBS ON  PRIMARY 
( NAME = N'SQL2012SBS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLFULL\MSSQL\DATA\SQL2012SBS.mdf' , SIZE = 7MB , MAXSIZE = UNLIMITED, FILEGROWTH = 10% ), 
FILEGROUP FG1  DEFAULT ( NAME = N'SQL2012SBSFG1_Dat1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLFULL\MSSQL\DATA\SQL2012SBS_1.ndf' , SIZE = 2MB , MAXSIZE = UNLIMITED, FILEGROWTH = 2MB)
                                                 
 LOG ON 
( NAME = N'SQL2012SBS_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLFULL\MSSQL\DATA\SQL2012SBS.ldf' , SIZE = 2MB , MAXSIZE = UNLIMITED , FILEGROWTH = 10MB )
GO
CREATE DATABASE SQL2012SBSFS ON PRIMARY
( NAME = N'SQL2012SBSFS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLFULL\MSSQL\DATA\SQL2012SBSFS.mdf' , SIZE = 7MB , MAXSIZE = UNLIMITED, FILEGROWTH = 10% ), 
 FILEGROUP DocumentFileStreamGroup 
( NAME = N'FileStreamDocuments', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLFULL\MSSQL\DATA\SQL2012SBSFS.ndf' )
 LOG ON 
( NAME = N'SQL2012SBSFS_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLFULL\MSSQL\DATA\SQL2012SBSFS.ldf' , SIZE = 2MB , MAXSIZE = UNLIMITED , FILEGROWTH = 10MB )
GO