USE SQL2012SBS
GO
CREATE SCHEMA Customers AUTHORIZATION dbo
GO
CREATE SCHEMA Orders AUTHORIZATION dbo
GO
CREATE SCHEMA Products AUTHORIZATION dbo
GO
CREATE SCHEMA LookupTables AUTHORIZATION dbo
GO
USE SQL2012SBSFS
GO
CREATE SCHEMA Products AUTHORIZATION dbo
GO
